apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-api
  template:
    metadata:
      labels:
        app: kubernetes-api
    spec:
      containers:
      - name: kubernetes-api
        image: <YOUR_DOCKER_HUB_ACCOUNT_NAME>/kubernetes-api:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-service
spec:
  selector:
    app: kubernetes-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
  type: LoadBalancer